name: eksctl
summary: a CLI for Amazon EKS
description: |
  eksctl is a simple CLI tool for creating clusters on EKS - Amazon's new
  managed Kubernetes service for EC2. It is written in Go, and uses
  CloudFormation.
  .
  You can create a cluster in minutes with just one command -
  eksctl create cluster!

grade: devel
confinement: strict
base: core24
adopt-info: eksctl

apps:
  eksctl:
    command: bin/eksctl
    plugs:
      - network

parts:
  eksctl:
    plugin: go
    source: https://github.com/eksctl-io/eksctl.git
    source-type: git
    override-pull: |
      craftctl default
      EKSCTL_TAG="$(git tag --sort=taggerdate | egrep -v '^(latest_release)' | tail -n 1)"
      set +e
      git describe --exact-match --tags $(git log -n1 --pretty='%h')
      retVal=$?
      set -e
      if [ $retVal -eq 0 ]; then
        craftctl set version="$EKSCTL_TAG"
      else
        GIT_REV="$(git rev-parse --short HEAD)"
        craftctl set version="$EKSCTL_TAG+$GIT_REV"
      fi
    override-build: |
      export GOPATH=$(realpath ../go)
      export GOBIN=$GOPATH/bin
      export PATH=$GOPATH/bin:$PATH

      make install-build-deps build
      mkdir -p "$CRAFT_PART_INSTALL/bin"
      cp -v eksctl "$CRAFT_PART_INSTALL/bin"
    build-snaps:
      - go/latest/stable
    build-packages:
      - git
      - make
